export const FETCH_REPOSITORIES_REQUEST = 'FETCH_REPOSITORIES_REQUEST';
export const FETCH_REPOSITORIES_FAILURE = 'FETCH_REPOSITORIES_FAILURE';
export const FETCH_REPOSITORIES_SUCCESS = 'FETCH_REPOSITORIES_SUCCESS';
export const UPDATE_REPOSITORIES = 'UPDATE_REPOSITORIES';
export const RESET_REPOSITORIES_STATE = 'RESET_REPOSITORIES_STATE';
